### ISSUE TITLE
1.7 regression: ia64 fails to build

### ISSUE THREAD

**Issue by AdrianBunk** [libunwind/libunwind#459]
https://buildd.debian.org/status/fetch.php?pkg=libunwind&arch=ia64&ver=1.7.0~rc2-1&stamp=1676246953&raw=0

```
In file included from ../include/dwarf-eh.h:29,
                 from mi/Gget_proc_info_in_range.c:23,
                 from mi/Lget_proc_info_in_range.c:4:
../include/dwarf.h:35:10: fatal error: dwarf-config.h: No such file or directory
   35 | #include "dwarf-config.h"
      |          ^~~~~~~~~~~~~~~~
```

@am11 This is caused by 4640cd26d5e045b738bacc20ed92a7cf8e801c0f, ia64 special here (see commit 9de666d141cffc4ec50e3a752d36fcf5cd752bb1).

**Comment by am11** [comment]
Fix is up: #460.

BTW, without `./configure --disable-tests ...`, ia64 tests build is failing:
```
/usr/libexec/gcc/ia64-unknown-linux-gnu/ld: /libunwind/src/.libs/libunwind.so: undefined reference to `_ULia64_init_local2'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1199: Gperf-simple] Error 1
make[1]: Leaving directory '/libunwind/tests'
make: *** [Makefile:621: all-recursive] Error 1
```
